name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Instala deps dentro de frontend
      - name: Install dependencies
        run: |
          cd frontend
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "⚠️ No se encontró package-lock.json, usando npm install"
            npm install --no-audit --no-fund
          fi

      # Compila el proyecto (Vite genera frontend/dist)
      - name: Build (warnings no rompen)
        run: |
          cd frontend
          CI=false npm run build

      # Verifica que dist exista y no esté vacío
      - name: Verify build output
        run: |
          if [ ! -d frontend/dist ] || [ -z "$(ls -A frontend/dist)" ]; then
            echo "❌ No se generó frontend/dist. Revisa el script de build."
            exit 1
          fi

      # 🚀 Deploy: subimos SOLO el artefacto ya construido para evitar 'too many files'
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DESERT_0C21E441E }}
          action: upload
          app_location: "frontend/dist"   # subir solo el build
          skip_app_build: true            # no recompilar en Azure
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DESERT_0C21E441E }}
          action: close