name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Instala deps con npm ci si existe lockfile; si no, instala normal
      - name: Install dependencies (robusto)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "⚠️ No hay package-lock.json, usando 'npm install'"
            npm install --no-audit --no-fund
          fi

      - name: Build (warnings no rompen)
        run: CI=false npm run build

      # Verifica que el build exista para evitar despliegues vacíos
      - name: Verify build output
        shell: bash
        run: |
          if [ ! -d dist ] || [ -z "$(ls -A dist)" ]; then
            echo "❌ No se generó 'frontend/dist'. Revisa el script de build."
            exit 1
          fi

      # Deploy del artefacto ya construido
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DESERT_0C21E441E }}
          action: upload
          app_location: "frontend"          # carpeta del app
          app_artifact_location: "frontend/dist"  # salida de Vite
          skip_app_build: true              # no recompilar en Azure
          api_location: ""
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PURPLE_DESERT_0C21E441E }}
          action: close